---
languages:
  - cpp:
      - emscripten: latest
      - ninja: 1.12.1
      - cmake: 3.27.0
  - javascript:
      - nvm: 0.40.3

git:
  clone_dir: "~/repos/from_eddy"
  repos:
    - https://github.com/kurekszymon/eddy.sh
    - https://github.com/kurekszymon/eddy2.sh

custom_scripts:
  # - configure_shell: echo "hello"
  # - configure_shell2: echo "hello2"

platform:
  manual_installation: true # will install all tools manually (e.g. using curl)
  brew: false # if you care about specific versions, use manual install due to how brew is handling formulaes versions
